### ISSUE TITLE
Can a more more detailed README.md

### ISSUE THREAD

**Issue by yipf42** [ZyJoey/icebox#3]
你好哇，该怎么启动项目呢？
我先使用了`node install` 和 `bower install`，然后尝试了下面两个方法启动项目
- [x]  `node ./server/index`     可以启动localhost:3000，但显示 `Cannot GET /`
- [x]  `使用fis3 release prod`   找不到编译后的文件

┑(￣Д ￣)┍

**Comment by ZyJoey** [comment]
因为编译后的前端代码可能与server不在同一根目录下 且配置端口号不同 所以先要配个代理~
1. 配置nginx
`
  server {
        listen       8080;
        server_name  localhost;

```
    #charset koi8-r;

    location / {
        root   D:\icebox;
        index  index.html index.htm;
    }
    location /server/ {
        proxy_pass http://127.0.0.1:3000/;
    }

 }`
```

2.根目录下安装依赖项
`npm install`
`bower install`

2.开启mongoDB 修改默认路径 `mongod --dbpath /data/icebox`
3.在server目录下输入命令`node index`
4.根目录下使用`fis3 release -wLc --dest D:\icebox`
5.浏览器中打开`localhost:8080`
6.自行注册个账号就可以运行了~

**Comment by yipf42** [comment]
Nice~go well without setting mongoDB path as yours.
while finding the register page  make few trouble on me.
thank you 
your code looks as good as my english

**Comment by yipf42** [comment]
![image](https://cloud.githubusercontent.com/assets/7829993/14411812/a2ce5504-ff85-11e5-86e4-1660b167f91a.png)

(-｡-;)

**Comment by ZyJoey** [comment]
重新上传了图片 更新下代码应该能看到了

**Comment by yipf42** [comment]
@ZyJoey 
![image](https://cloud.githubusercontent.com/assets/7829993/14447541/7c42dce8-0093-11e6-9022-35c560705dfa.png)
**# nice啊,**
![image](https://cloud.githubusercontent.com/assets/7829993/14447579/c6fab648-0093-11e6-99c5-1cca2cd7d5d9.png)
**# horrible啊，**

**Comment by ZyJoey** [comment]
图片上传功能还没测试= =

**Comment by yipf42** [comment]
only sign in by touch?

**Comment by yipf42** [comment]
There are some ads when searching food

**Comment by ZyJoey** [comment]
说~！

**Comment by ypf93** [comment]
.....不用搭理我的，我就无聊看看
